### ISSUE TITLE
Concatenating multiple tables with footnote on every page

### ISSUE THREAD

**Issue by kmkramer23** [Merck/r2rtf#54] opened 2021-09-07 19:49 UTC
If I concatenate multiple tables where the first table in the list contains the footnote and encode it with the parameter page_footnote = 'all', it will only print the footnote on the last page of a multi page report.  Is this expected behavior when concatenating multiple tables or should the footnote display on every page?

**Comment by elong0527** [comment] 2021-09-08 03:03
Those `page_xxx` arguments in `rtf_encode` are not fully supported when the input is a list. 

The original purpose of concatenate multiple data.frame is to design a table in one page. And I have not find a proper way to handle the logic in `rtf_encode_list`.   

It shall provide an error message when `page_footnote = "all"`. The error message now is displayed properly in #55

For example, the code below shall encounter error. 

```
devtools::load_all()
library(dplyr)

t1 <- head(cars) %>% 
  rtf_title("tmp") %>%
  rtf_body() %>%
  rtf_footnote("footnote")

t2 <- iris %>% 
  rtf_body()

list(t1, t2) %>% 
  rtf_encode(page_footnote = "all") %>%
  write_rtf("tmp.rtf")
```

**Comment by elong0527** [comment] 2021-11-04 22:56
The issue is closed as proper message is provided to indicate the limitation. And there is no plan to enhance this feature in the near future.

**Closed by elong0527** 2021-11-04 22:56 UTC
