### ISSUE TITLE
'unicode_latex' not found

### ISSUE THREAD

**Issue by kmkramer23** [Merck/r2rtf#50] opened 2021-09-02 18:35 UTC
If I import the r2rtf package and try to use the functions in the package using full namespace syntax without calling the libname(r2rtf) first I receive the following error when it tries to call r2rtf::rtf_encode(page_footnote = "all") :

Error in as.hexmode(unicode_latex$unicode) : 
  object 'unicode_latex' not found

**Comment by elong0527** [comment] 2021-09-02 21:26
Thanks for reporting the issue. Could you provide a reproducible example using reprex? Thanks!

https://reprex.tidyverse.org/

**Comment by kmkramer23** [comment] 2021-09-03 00:40
Below is some sample code using your r2rtf_adae data that generated the same error.

import::from(tidyr, .all=TRUE)
import::from(dplyr, .all=TRUE)
import::from(r2rtf, .all=TRUE)  # Simulate importing from a package generates an error when it hits r2rtf::rtf_encode

# This is the error that gets generated
# Error in as.hexmode(unicode_latex$unicode) :
#    object 'unicode_latex' not found

# library(r2rtf)  # If I uncomment this it runs fine


gen_error <- function() {

    tbl <- r2rtf::r2rtf_adae %>%
        dplyr::count(TRTA, AEDECOD) %>%
        tidyr::pivot_wider(names_from = TRTA, values_from = n, values_fill = 0)

    tbl %>%
        r2rtf::rtf_page(orientation = "landscape",
                        col_width = 9.25,
                        margin = c(0.75, 1, 1.5, 1, 1, 1), nrow = 27, border_first = "single", border_last = "single") %>%
        r2rtf::rtf_title(title = c("Title1", "Title 2"),
                         text_format = "b",
                         text_font_size = 11,
                         text_font = 4
        ) %>%
        r2rtf::rtf_footnote(footnote =  c("Footnote 1", "Footnote2", "Footnote 3", "Footnote 4"),
                            as_table = FALSE
        ) %>%
        r2rtf::rtf_colheader(colheader = "Header 1 | Header 2 | Header 3 | Header 4",
                             col_rel_width = c(3.25, 1, 1, 1),
                             border_left = c("single", "", "", ""),
                             border_right = c("", "", "", "single"),
                             text_justification = c("c", "c", "c","c"),
                             text_font = 4,
        ) %>%
        r2rtf::rtf_body(
            col_rel_width = c(3.25, 1, 1, 1),
            border_left = c("single", "", "", ""),
            border_right = c("", "", "", "single"),
            text_justification = c("c", "c", "c","c"),
            text_font = 4,
        ) %>%
        r2rtf::rtf_page_footer(text = "Page \\pagenumber of  \\pagefield") %>%
        r2rtf::rtf_encode(page_footnote = "all") %>%
        r2rtf::write_rtf("./issue_test.rtf")
}

gen_error()

________________________________

**Comment by elong0527** [comment] 2021-09-03 01:10
I feel it is related to the `import` package instead of `r2rtf`.  

The error happen because the internal function of r2rtf requires to use internal data `unicode_latex` saved in https://github.com/Merck/r2rtf/tree/master/data

This is a standard way to save data in an R package, but seems `import::from` did not recognize this. 
https://r-pkgs.org/data.html#data-sysdata

I would suggest to use `library(r2rtf)`   at current stage.

**Comment by kmkramer23** [comment] 2021-09-03 04:13
If I add unicode_latex <- r2rtf::unicode_latex before I build the report then it runs without error.

**Comment by kmkramer23** [comment] 2021-09-03 19:23
I downloaded the source code and tested if the unicode_latex was stored in the sysdata.rda folder by running the command
usethis::use_data(unicode_latex, internal = TRUE) and it fixed the issue.  Would you be able to add this to the package?

**Comment by elong0527** [comment] 2021-09-03 19:39
Thanks for pointing the issue! This is a good point and I will evaluate and fix them.

**Comment by elong0527** [comment] 2021-09-03 22:16
Fixed in #51

**Closed by elong0527** 2021-09-03 22:16 UTC
